const SEASONS_AVAILABLE = [
  {year:'1940', file:'1940.json', champs:{AL:'Cincinnati Reds', NL:'Cincinnati Reds'}},
  {year:'1941', file:'1941.json', champs:{AL:'New York Yankees', NL:'Brooklyn Dodgers'}},
  {year:'1942', file:'1942.json', champs:{AL:'St. Louis Cardinals', NL:'St. Louis Cardinals'}},
  {year:'1943', file:'1943.json', champs:{AL:'New York Yankees', NL:'St. Louis Cardinals'}},
  {year:'1944', file:'1944.json', champs:{AL:'St. Louis Browns', NL:'St. Louis Cardinals'}},
  {year:'1945', file:'1945.json', champs:{AL:'Detroit Tigers', NL:'Chicago Cubs'}},
  {year:'1946', file:'1946.json', champs:{AL:'Boston Red Sox', NL:'St. Louis Cardinals'}},
  {year:'1947', file:'1947.json', champs:{AL:'New York Yankees', NL:'Brooklyn Dodgers'}},
  {year:'1948', file:'1948.json', champs:{AL:'Cleveland Indians', NL:'Boston Braves'}},
  {year:'1949', file:'1949.json', champs:{AL:'New York Yankees', NL:'Brooklyn Dodgers'}},
  {year:'1950', file:'1950.json', champs:{AL:'New York Yankees', NL:'Philadelphia Phillies'}},
  {year:'1951', file:'1951.json', champs:{AL:'New York Yankees', NL:'New York Giants'}},
  {year:'1952', file:'1952.json', champs:{AL:'New York Yankees', NL:'Brooklyn Dodgers'}},
  {year:'1953', file:'1953.json', champs:{AL:'New York Yankees', NL:'Brooklyn Dodgers'}},
  {year:'1954', file:'1954.json', champs:{AL:'Cleveland Indians', NL:'New York Giants'}},
  {year:'1955', file:'1955.json', champs:{AL:'New York Yankees', NL:'Brooklyn Dodgers'}},
  {year:'1956', file:'1956.json', champs:{AL:'New York Yankees', NL:'Brooklyn Dodgers'}},
  {year:'1957', file:'1957.json', champs:{AL:'New York Yankees', NL:'Milwaukee Braves'}},
  {year:'1958', file:'1958.json', champs:{AL:'Chicago White Sox', NL:'Milwaukee Braves'}},
  {year:'1959', file:'1959.json', champs:{AL:'Chicago White Sox', NL:'Los Angeles Dodgers'}},
  {year:'1960', file:'1960.json', champs:{AL:'New York Yankees', NL:'Pittsburgh Pirates'}},
  {year:'1961', file:'1961.json', champs:{AL:'New York Yankees', NL:'Cincinnati Reds'}},
  {year:'1962', file:'1962.json', champs:{AL:'New York Yankees', NL:'San Francisco Giants'}},
  {year:'1963', file:'1963.json', champs:{AL:'New York Yankees', NL:'Los Angeles Dodgers'}},
  {year:'1964', file:'1964.json', champs:{AL:'New York Yankees', NL:'St. Louis Cardinals'}},
  {year:'1965', file:'1965.json', champs:{AL:'Minnesota Twins', NL:'Los Angeles Dodgers'}},
  {year:'1966', file:'1966.json', champs:{AL:'Baltimore Orioles', NL:'Los Angeles Dodgers'}},
  {year:'1967', file:'1967.json', champs:{AL:'Boston Red Sox', NL:'St. Louis Cardinals'}},
  {year:'1968', file:'1968.json', champs:{AL:'Detroit Tigers', NL:'St. Louis Cardinals'}},
  {year:'1969', file:'1969.json', champs:{AL:'Baltimore Orioles', NL:'New York Mets'}},
  {year:'1970', file:'1970.json', champs:{AL:'Baltimore Orioles', NL:'Cincinnati Reds'}},
  {year:'1971', file:'1971.json', champs:{AL:'Baltimore Orioles', NL:'Pittsburgh Pirates'}},
  {year:'1972', file:'1972.json', champs:{AL:'Oakland Athletics', NL:'Cincinnati Reds'}},
  {year:'1973', file:'1973.json', champs:{AL:'Oakland Athletics', NL:'New York Mets'}},
  {year:'1974', file:'1974.json', champs:{AL:'Oakland Athletics', NL:'Los Angeles Dodgers'}},
  {year:'1975', file:'1975.json', champs:{AL:'Boston Red Sox', NL:'Cincinnati Reds'}},
  {year:'1976', file:'1976.json', champs:{AL:'New York Yankees', NL:'Cincinnati Reds'}},
  {year:'1977', file:'1977.json', champs:{AL:'New York Yankees', NL:'Los Angeles Dodgers'}},
  {year:'1978', file:'1978.json', champs:{AL:'New York Yankees', NL:'Los Angeles Dodgers'}},
  {year:'1979', file:'1979.json', champs:{AL:'Baltimore Orioles', NL:'Pittsburgh Pirates'}},
  {year:'1980', file:'1980.json', champs:{AL:'Kansas City Royals', NL:'Philadelphia Phillies'}},
  {year:'1981', file:'1981.json', champs:{AL:'New York Yankees', NL:'Los Angeles Dodgers'}},
  {year:'1982', file:'1982.json', champs:{AL:'Milwaukee Brewers', NL:'St. Louis Cardinals'}},
  {year:'1983', file:'1983.json', champs:{AL:'Baltimore Orioles', NL:'Philadelphia Phillies'}},
  {year:'1984', file:'1984.json', champs:{AL:'Detroit Tigers', NL:'San Diego Padres'}},
  {year:'1985', file:'1985.json', champs:{AL:'Kansas City Royals', NL:'St. Louis Cardinals'}},
  {year:'1986', file:'1986.json', champs:{AL:'Boston Red Sox', NL:'New York Mets'}},
  {year:'1987', file:'1987.json', champs:{AL:'Minnesota Twins', NL:'St. Louis Cardinals'}},
  {year:'1988', file:'1988.json', champs:{AL:'Oakland Athletics', NL:'Los Angeles Dodgers'}},
  {year:'1989', file:'1989.json', champs:{AL:'Oakland Athletics', NL:'San Francisco Giants'}},
  {year:'1990', file:'1990.json', champs:{AL:'Oakland Athletics', NL:'Cincinnati Reds'}},
  {year:'1991', file:'1991.json', champs:{AL:'Minnesota Twins', NL:'Atlanta Braves'}},
  {year:'1992', file:'1992.json', champs:{AL:'Toronto Blue Jays', NL:'Atlanta Braves'}},
  {year:'1993', file:'1993.json', champs:{AL:'Toronto Blue Jays', NL:'Philadelphia Phillies'}},
  {year:'1994', file:'1994.json', champs:{AL:'', NL:''}},  // strike-shortened
  {year:'1995', file:'1995.json', champs:{AL:'Cleveland Indians', NL:'Atlanta Braves'}},
  {year:'1996', file:'1996.json', champs:{AL:'New York Yankees', NL:'Atlanta Braves'}},
  {year:'1997', file:'1997.json', champs:{AL:'Cleveland Indians', NL:'Florida Marlins'}},
  {year:'1998', file:'1998.json', champs:{AL:'New York Yankees', NL:'San Diego Padres'}},
  {year:'1999', file:'1999.json', champs:{AL:'New York Yankees', NL:'New York Mets'}},
  {year:'2000', file:'2000.json', champs:{AL:'New York Yankees', NL:'New York Mets'}},
  {year:'2001', file:'2001.json', champs:{AL:'Seattle Mariners', NL:'Arizona Diamondbacks'}},
  {year:'2002', file:'2002.json', champs:{AL:'Minnesota Twins', NL:'San Francisco Giants'}},
  {year:'2003', file:'2003.json', champs:{AL:'New York Yankees', NL:'Florida Marlins'}},
  {year:'2004', file:'2004.json', champs:{AL:'Boston Red Sox', NL:'St. Louis Cardinals'}},
  {year:'2005', file:'2005.json', champs:{AL:'Chicago White Sox', NL:'Houston Astros'}},
  {year:'2006', file:'2006.json', champs:{AL:'Detroit Tigers', NL:'St. Louis Cardinals'}},
  {year:'2007', file:'2007.json', champs:{AL:'Boston Red Sox', NL:'Colorado Rockies'}},
  {year:'2008', file:'2008.json', champs:{AL:'Tampa Bay Rays', NL:'Philadelphia Phillies'}},
  {year:'2009', file:'2009.json', champs:{AL:'New York Yankees', NL:'Philadelphia Phillies'}},
  {year:'2010', file:'2010.json', champs:{AL:'Texas Rangers', NL:'San Francisco Giants'}},
  {year:'2011', file:'2011.json', champs:{AL:'Texas Rangers', NL:'St. Louis Cardinals'}},
  {year:'2012', file:'2012.json', champs:{AL:'Detroit Tigers', NL:'San Francisco Giants'}},
  {year:'2013', file:'2013.json', champs:{AL:'Boston Red Sox', NL:'St. Louis Cardinals'}},
  {year:'2014', file:'2014.json', champs:{AL:'Kansas City Royals', NL:'San Francisco Giants'}},
  {year:'2015', file:'2015.json', champs:{AL:'Kansas City Royals', NL:'New York Mets'}},
  {year:'2016', file:'2016.json', champs:{AL:'Cleveland Indians', NL:'Chicago Cubs'}},
  {year:'2017', file:'2017.json', champs:{AL:'Houston Astros', NL:'Los Angeles Dodgers'}},
  {year:'2018', file:'2018.json', champs:{AL:'Boston Red Sox', NL:'Los Angeles Dodgers'}},
  {year:'2019', file:'2019.json', champs:{AL:'Houston Astros', NL:'Washington Nationals'}},
  {year:'2020', file:'2020.json', champs:{AL:'Tampa Bay Rays', NL:'Los Angeles Dodgers'}},
  {year:'2021', file:'2021.json', champs:{AL:'Houston Astros', NL:'Atlanta Braves'}},
  {year:'2022', file:'2022.json', champs:{AL:'Houston Astros', NL:'Philadelphia Phillies'}},
  {year:'2023', file:'2023.json', champs:{AL:'Texas Rangers', NL:'Arizona Diamondbacks'}},
  {year:'2024', file:'2024.json', champs:{AL:'New York Yankees', NL:'Los Angeles Dodgers'}},
  {year:'2025', file:'2025.json', champs:{AL:'', NL:''}},
];